[package]
name = "cargo-proc-macro"
description = "Because starting a proc-macro project shouldn't be this painful still."
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
license = "EUPL-1.2"

[dependencies]
gumdrop = "0.8.0"
env_logger = "0.7.1"
log = "0.4.11"
